# backend/services/astrology_constants.py

NAKSHATRA_NAMES = [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishta",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
]
YOGA_NAMES = [
    "Vishkumbha",
    "Priti",
    "Ayushman",
    "Saubhagya",
    "Shobhana",
    "Atiganda",
    "Sukarma",
    "Dhriti",
    "Shoola",
    "Ganda",
    "Vriddhi",
    "Dhruva",
    "Vyaghata",
    "Harshana",
    "Vajra",
    "Siddhi",
    "Vyatipata",
    "Variyana",
    "Parigha",
    "Shiva",
    "Siddha",
    "Sadhya",
    "Shubha",
    "Shukla",
    "Brahma",
    "Indra",
    "Vaidhriti",
]
KARANA_NAMES = [
    "Bava",
    "Balava",
    "Kaulava",
    "Taitila",
    "Gara",
    "Vanija",
    "Vishti",
    "Shakuni",
    "Chatushpada",
    "Nagava",
    "Kimstughna",
]

TITHI_NAMES = [
    "Pratipada",
    "Dvitiya",
    "Tritiya",
    "Chaturthi",
    "Panchami",
    "Shashthi",
    "Saptami",
    "Ashtami",
    "Navami",
    "Dashami",
    "Ekadashi",
    "Dwadashi",
    "Trayodashi",
    "Chaturdashi",
    "Purnima",
    "Amavasya",
] * 2  # Repeat for Shukla & Krishna Paksha

MONTH_NAMES = [
    "Chaitra",
    "Vaishakha",
    "Jyeshtha",
    "Ashadha",
    "Shravana",
    "Bhadrapada",
    "Ashwin",
    "Kartik",
    "Margashirsha",
    "Pausha",
    "Magha",
    "Phalguna",
]

SENSITIVE_POINTS = {
    "Mandi": lambda jd: (jd * 1.011) % 360,
    "Gulika": lambda jd: (jd * 1.022) % 360,
    "Bhava Lagna": lambda jd: (jd * 1.033) % 360,
    "Hora Lagna": lambda jd: (jd * 1.044) % 360,
    "Ghati Lagna": lambda jd: (jd * 1.055) % 360,
    "Vighati Lagna": lambda jd: (jd * 1.066) % 360,
    "Varnada Lagna": lambda jd: (jd * 1.077) % 360,
    "Sree Lagna": lambda jd: (jd * 1.088) % 360,
    "Pranpada Lagna": lambda jd: (jd * 1.099) % 360,
    "Indu Lagna": lambda jd: (jd * 1.110) % 360,
    "Bhrigu Bindu": lambda jd: (jd * 1.121) % 360,
    "Dhooma": lambda jd: (jd * 1.132) % 360,
    "Vyatipata": lambda jd: 360 - (jd * 1.132) % 360,
    "Parivesha": lambda jd: (jd * 1.143) % 360,
    "Indra Chapa": lambda jd: (jd * 1.154) % 360,
    "Upaketu": lambda jd: (jd * 1.165) % 360,
    "Kaala": lambda jd: 360 - (jd * 1.165) % 360,
    "Mrityu": lambda jd: (jd * 1.176) % 360,
    "Artha Prahara": lambda jd: (jd * 1.187) % 360,
    "Yama Ghantaka": lambda jd: (jd * 1.198) % 360,
    "Prana Sphuta": lambda jd: (jd * 1.209) % 360,
    "Deha Sphuta": lambda jd: (jd * 1.220) % 360,
    "Mrityu Sphuta": lambda jd: (jd * 1.231) % 360,
    "Sookshma Trisphuta": lambda jd: (jd * 1.242) % 360,
    "Tithi Sphuta": lambda jd: (jd * 1.253) % 360,
    "Kshetra Sphuta": lambda jd: (jd * 1.264) % 360,
    "Beeja Sphuta": lambda jd: (jd * 1.275) % 360,
    "Trisphuta": lambda jd: (jd * 1.286) % 360,
    "Chatusphuta": lambda jd: (jd * 1.297) % 360,
    "Panchasphuta": lambda jd: (jd * 1.308) % 360,
    "Kunda": lambda jd: (jd * 1.319) % 360,
    "Yoga Sphuta": lambda jd: (jd * 1.330) % 360,
    "Avayoga Sphuta": lambda jd: (jd * 1.341) % 360,
}
